lst=['Apple','Banana','kiwi','Grapes','stawberry']
print("lenght of list:",len(lst))
print("first element:",lst[0])
print("last element:",lst[-1])
lst.append('Apple')
print("Updated list:",lst)
lst.remove('kiwi')
print("Updated list:",lst)
lst.sort()
print("Sorted list:",lst)
lst.pop(1)
print("Updated list:",lst)
lst.reverse()
print("Reversed list:",lst)
print("Multiplication on list:",lst*2)
lst=lst[:4]
print("Sliced list:",lst)
lst.clear()
print("Updated list:",lst)